### ISSUE TITLE
[Bug] Ilex Forest Grass doesn't get recognized as grass with moveToGrass()

### ISSUE THREAD

**Issue by 0x526f6d656f** [Silv3rPRO/proshine#104]
Title

**Comment by ScrPits** [comment]
^ needs "BattleArea" detection
getMapName = getBattleArea normal / headbutt n dig / surfing
normal pulls battle area grass and map (for caves)
headbutt n dig (if any active on map clear them if possible)
Surfing (to finish off the map battle areas)

Pro's: will help script writers as theyd just need to define "normal or Surfing" in their leveling location. and could allow changing battling spots on map.

cons: rectangle wouldnt work/players would be nearly everywhere in leveling map 
(ilex forest acts close enough to a cave which would map the whole map a battling area
