### ISSUE TITLE
[Bug] Outdated Client?

### ISSUE THREAD

**Issue by Dodgethestorm** [Silv3rPRO/proshine#121]
I keep trying to use PROShine, but it always comes up with this text

Running PROShine by Silv3r, version 2.7.1.0
Connecting to the server...
Connected, authenticating...
Authentication failed: Outdated client, please wait for an update
Disconnected from the server.

Unsure what the problem is

**Comment by 0x526f6d656f** [comment]
It literally tells you, that the client is outdated.

Wait for an update or download a fan-made updated version on the forums.

**Comment by Dodgethestorm** [comment]
XD
