### ISSUE TITLE
isAlreadyCaught() not detected

### ISSUE THREAD

**Issue by ghost** [Silv3rPRO/proshine#14]
I have started Hoenn region and made a script while in Route 104.

Script on Battle Action:

```
function onBattleAction()
    if isWildBattle() and isOpponentShiny() then
        if useItem("Ultra Ball") or useItem("Great Ball") or useItem("Pokeball") then
            return
        end
    end

    if isWildBattle() and isAlreadyCaught() == "false" then
        if useItem("Ultra Ball") or useItem("Great Ball") or useItem("Pokeball") then
            return
        end
    end

    if getActivePokemonNumber() == 1 then
        return attack() or sendUsablePokemon() or run() or sendAnyPokemon()
    else
        return run() or attack() or sendUsablePokemon() or sendAnyPokemon()
    end
end
```

It doesn't throw any Pokeball and just attacks the opponent when I encounter a pokemon I haven't catched; I suspect the `isAlreadyCaught()` function is not working properly, so far the same script has worked in Kanto and Jhoto.

**Comment by Silv3rPRO** [comment]
`isAlreadyCaught()` returns a boolean, not a string.

Can you try again with this line instead?

``` lua
if isWildBattle() and isAlreadyCaught() == false then
```

Or, even better:

``` lua
if isWildBattle() and not isAlreadyCaught() then
```

**Comment by ghost** [comment]
Ah you are right, I didn't notice the quotation marks ***_facepalm**_*, thank you again, I'll close this issue.
