### ISSUE TITLE
getPokemonOriginalTrainer() and getPokemonOriginalTrainerFromPC() return an integer

### ISSUE THREAD

**Issue by g0ldPRO** [Silv3rPRO/proshine#15]
`getPokemonOriginalTrainer()` and `getPokemonOriginalTrainerFromPC()` should return the name of the trainer but return an unidentified integer instead.

**Comment by ghost** [comment]
I have detected the unidentified integer, the number it returns is the **Base Exp.** of the pokemon, which is a variable used to calculate how much exp any of your pokemon get when defeating **that** pokemon.

**Comment by ghost** [comment]
Pull request #16 should correct this bug. Let me know if it works ;)

**Comment by g0ldPRO** [comment]
I did not expect anyone to do the job for me, pull request merged. Thank you!

**Comment by ghost** [comment]
No problem,It's a smal fix but I'm still learning and I hope I can contribute more with big improvements in the future.
