### ISSUE TITLE
Receiving the error " Object reference not set to an instance of an object." when the trainer encounters a Pokemon. is effecting 100% of all my scripts that involve attacking that previously worked.  Scripts that catch pokemon and run away from the rest are uneffected.

### ISSUE THREAD

**Issue by 423956** [Silv3rPRO/proshine#18]
Object reference not set to an instance of an object
THIS IS NOT DUE TO SCRIPTING.
https://proshine-bot.ml/viewtopic.php?id=905

As you can see someone reffered me to come here after working out that it is NOT the SCRIPT that is causing this bug.

**Comment by 423956** [comment]
This is not 'No action executed'.
This is Object reference not set to an instance of an object.
This effects me and 3 other people. We can use scripts that work for other people, but they will not work for us.

**Comment by g0ldPRO** [comment]
The previous issue can be reopened with more information on how to reproduce the bug.  
Do not create duplicate as it only reduce the readability of the tickets.

Duplicate of #17
