### ISSUE TITLE
Surfing

### ISSUE THREAD

**Issue by Plmane** [Silv3rPRO/proshine#3]
The name of the badge we need in order to Fish/Surf is: [Balance Badge](http://bulbapedia.bulbagarden.net/wiki/Badge#Balance_Badge)

**Comment by Silv3rPRO** [comment]
Surfing should now be working after this commit: https://github.com/Silv3rPRO/proshine/commit/34679828ea4dce877f78ec91f0798b441f8911d7

I haven't tested yet so let me know if this is not working.
