### ISSUE TITLE
keep running away

### ISSUE THREAD

**Issue by meovince08** [Silv3rPRO/proshine#30]
I am using my bot. After maybe 15 mins my pokemon doesnt have any skills anymore it just keep running away not going in the poke center for heal. How could i fix this?

**Comment by Khristian-kun** [comment]
without posting the script code anyone can't help you

**Comment by Silv3rPRO** [comment]
This bug is probably fixed, some moves were not handled properly by the `isPokemonUsable` function.
It it happens again, we are going to need the script you are using and the moves of your Pokémon to investigate.
