### ISSUE TITLE
[Request] .proto files

### ISSUE THREAD

**Issue by Tarnadas** [Silv3rPRO/proshine#31]
Hi,

This is not an issue bot more a request.
Do you have any uncompiled .proto files, that you would share? I want to make an Android application, because I'm sick of the bad interface they use in their Android App. It's basically the same as their desktop client^^
Also do you know an easy way to extract their assets?

**Comment by Silv3rPRO** [comment]
I must admit that I have no idea what a `.proto` file is.
If you are looking for the protocol, you should look at this file:
https://github.com/Silv3rPRO/proshine/blob/master/PROProtocol/GameClient.cs
Or this repository:
https://github.com/g0ldPRO/PROWireshark

**Comment by johnnymo87** [comment]
https://developers.google.com/protocol-buffers/

@Tarnadas I believe PRO does not serialize its data via protocol buffers. The content Silver mentioned is a great place to start if you want to study how clients can communicate with the PRO server. Here's a tutorial for the Wireshark approach: https://proshine-bot.com/thread-148.html
