### ISSUE TITLE
PC Api are Broken

### ISSUE THREAD

**Issue by Rympex** [Silv3rPRO/proshine#33]
Hi Silver :) today i try fix PC APIs
But i don't have enough skill

i found the packet and how is change with this last update

befor this update for ask pokemons on Box 1:  was range 1 to 15

**Packet:      M|.|1|.|15|.\**

now no need anymore this calc, is automatic on the server
Now for ask pokemon is Box 1: packet is 

(Boxid - 1)
**Packet:     M|.|0|.|ID|.\**

now is possible retrive a box directly with a pokemon name, Example
i want ask all Oddish in box 1 ( first 15 Oddish ), packet is 
(Boxid - 1)

**Packet:     M|.|0|.|Oddish|.\**

Oddish or oddish is the same, case insensitive
Thanks :3

**Comment by Silv3rPRO** [comment]
Fixed in https://github.com/Silv3rPRO/proshine/commit/6555ee3e3f4b1e29caa7e9d0ae5433c982f9cfd6.
