### ISSUE TITLE
isAutoEvolve() attempt to call a nil value

### ISSUE THREAD

**Issue by PotatoBlood** [Silv3rPRO/proshine#41]
isAutoEvolve()
DisableAutoEvolve()

attempt to call a nil value

**Comment by MeltWS** [comment]
Seems to be working for me with this: 
`function onStart()
        if isAutoEvolve() then
            disableAutoEvolve()
        else
            enableAutoEvolve()
        end
end`

**Comment by PotatoBlood** [comment]
this can be closed, I used caps where it wasn't needed.
