### ISSUE TITLE
talkToNpc() Neighbouring cells

### ISSUE THREAD

**Issue by MeltWS** [Silv3rPRO/proshine#43]
Seems like the pathfinding does not account correctly for neighbouring cells:
![image](https://cloud.githubusercontent.com/assets/15630634/19401916/36df7ab4-925e-11e6-9b48-e3578487fd48.png)

This happens because TalkToNpc calls `path.MoveTo(x, y, requiredDistance);` with 1 distance.
I think It would need to account for the ability to interact with the npc aswell. and move to the correct cell directly.

**Comment by MeltWS** [comment]
I came up with a somewhat ok~ fix, if you want to check it: [https://github.com/MeltWS/proshine/commit/c22f419988b238146df8bad6a021c53090e792e6](url)

It's not fully supported as it's possible they are other case like this one with different colliders, but it can be built-up.

**Comment by MeltWS** [comment]
Just found out the other day that this does not work if you already are at 1 range of the NPC, it also needs a check to know if it can interact with it.

**Comment by Silv3rPRO** [comment]
I cannot manage to fix this problem.

If I add a check to make sure the interaction is possible (see commit above), it breaks some NPC we can interact with from behind an obstacle.
The official game client is not even checking if the interaction is possible, only the distance.

Do you have an example of where this bug occurs so I can check what's going on with this item?

**Comment by MeltWS** [comment]
Yes the picture in my example is from route 3.
What are the npcs you can interact over an obstacle?

**Comment by Silv3rPRO** [comment]
Thanks. I just checked and the check is indeed done server-side, not client-side.
The client is sending the "talk to npc" packet even when there is an obstacle.

As for the NPC we can interact with, basically any NPC inside a wall (buttons, elevators) or placed on a table.

**Comment by MeltWS** [comment]
So what happens when the client sends talk to npc over a wall that is not
interractable? Does it get a negative response we should use?
I'm guessing what is happening server side is as simple as a check with
colliders. Wall button elevator are inside walls that pass the check and
outside wall at different levels fail it.

**Comment by Silv3rPRO** [comment]
6486bacf84b7c348bdd9bb40d1dace1250c1b01a should fix the problem.
I am only checking for the collision 14 since it looks like this is the only one blocking the interactions.

**Comment by Silv3rPRO** [comment]
> So what happens when the client sends talk to npc over a wall that is not interractable?

Nothing special, the server is sending the "end of npc dialog" packet.

**Comment by MeltWS** [comment]
Working for me now, closing.
