### ISSUE TITLE
Proshine Pathfinding in cascades.

### ISSUE THREAD

**Issue by MeltWS** [Silv3rPRO/proshine#47]
The cascades are one way threw. It seems like the bot tries to go threw them like they are bi directionals.

Example in Meteor falls 1F 1R in Hoenn:
To reproduce be on the bottom entrance cell `19, 46` and `moveToCell(46, 22)` which is the top side exit. 

![image](https://cloud.githubusercontent.com/assets/15630634/20034603/b544807c-a3c3-11e6-9d3e-851cb4df3f86.png)
![image](https://cloud.githubusercontent.com/assets/15630634/20034608/cea351c4-a3c3-11e6-86fb-e73a3019cd58.png)
Same thing happens with the bottom right cascade:
![image](https://cloud.githubusercontent.com/assets/15630634/20034610/fe045954-a3c3-11e6-83b2-215e3124b6be.png)

**Comment by Silv3rPRO** [comment]
I could not find anything about cascades in the source code, I don't know how the client handles them.

Since I do not have any character in Hoenn, I cannot check the map easily.

Is there any NPC or something special on these cells? Do they have a special collider value?

**Comment by MeltWS** [comment]
Colliders are 5, so it's water, I don't think they are Npcs there was only 6 of them on the map.
If you want an account with Hoenn access you can contact me on discord I don't mind sharing one.
