### ISSUE TITLE
Releasing from the PC can't be done.

### ISSUE THREAD

**Issue by Zonz** [Silv3rPRO/proshine#49]
The releasePokemonFromPC method seems to do nothing, and only returns false. The bot will time-out if you attempt to call the function multiple times, even if you call it every frame.

**Comment by Silv3rPRO** [comment]
This should now be fixed: f1df9ea8fad307f13c6a94db4eee6df3a77123ed

Note that you still have to call the function two times since there is a confirmation message ("Are you sure you want to release...?") the first time.
