### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by lFeeeeelipe** [Silv3rPRO/proshine#53]
Hello, I'm trying to use the bot, but it's giving this message:

_[23:08:23] Connected, authenticating...
[23:08:23] Authentication failed: Outdated client, please wait for an update
[23:08:23] Disconnected from the server._

How can I solve this? Thank you

**Comment by nicklaspaepke** [comment]
i would like to know as well

**Comment by Crazy3001** [comment]
Wait until the bot is updated, or go on Discord and I'll give you what you need

**Comment by Silv3rPRO** [comment]
Like the message says, it means the protocol version used by the bot is incorrect.

You can either wait for an update or edit the protocol yourself according to the latest changes.
