### ISSUE TITLE
false isPokemonUsable(int) return

### ISSUE THREAD

**Issue by ghost** [Silv3rPRO/proshine#6]
some Pokémons have a false isPokemonUsable return,

they return true (is usable)
but do not attack(return attack() or run() they choose run)
example is gyarados and gastly/haunter

**Comment by g0ldPRO** [comment]
Is it possible that your last usable moves were nullified by the enemy type?
For instance _normal_ is nullified by _ghost_.

**Comment by ghost** [comment]
unknown, route 19 to seafoam Islands, i think nothing can nullify a ghosttype there or a Dragon type

**Comment by Silv3rPRO** [comment]
We are going to need the following information to fix this bug:
- The name, the 4 moves and the remaining PP of the current pokémon.
- The name of the opponent pokémon.

It can easily be done using `log()` in a script.
