### ISSUE TITLE
[question] sendCreateCharacter

### ISSUE THREAD

**Issue by M1L4** [Silv3rPRO/proshine#96]
**[Question]**
I would like to modify the gender of the bots being created. Any idea what I have to modify for that? I only found following, which doesn't inlcude gender - in GameClient.cs:

`public void SendCreateCharacter(int hair, int colour, int tone, int clothe, int eyes)`

**Comment by Silv3rPRO** [comment]
The `tone` variable is used to determine the gender.

`[0-3]`: male
`[4-7]`: female

**Comment by M1L4** [comment]
wow - never would have thought that - many thanks :D
